---
- name: "Install JEnv"
  homebrew:
    name: jenv
    state: installed
  tags:
    - java

- name: "Install Jdk 8"
  homebrew_cask:
    name: adoptopenjdk8
    state: installed
  tags:
    - java
  ignore_errors: yes

- name: "Install maven"
  homebrew:
    name: maven
    state: installed
  tags:
    - java
  ignore_errors: yes

- name: "Install Jdk 11"
  homebrew_cask:
    name: adoptopenjdk11
    state: installed
  tags:
    - java
    - java11
  ignore_errors: yes
